# Generated by Django 5.0 on 2024-11-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0018_alter_student_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="student_email",
            field=models.EmailField(
                default="H7oPj@example.com", max_length=254, unique=True
            ),
        ),
    ]
