# Generated by Django 5.0 on 2024-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0022_alter_student_profile_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_profile",
            name="student_email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
